//
// Created by Darius on 23.08.2017.
//

#ifndef AIRRESPECK_STEP_COUNT_H
#define AIRRESPECK_STEP_COUNT_H

#define STEP_THRESHOLD 1.02
#define STEP_MIN_DELAY_MS 120
#define NUM_STEPS_UNTIL_COUNT_WALKING 4
#define MAX_ALLOWED_DEVIATION_FROM_MEAN_DISTANCE 6
#define NUM_SAMPLES_UNTIL_STATIC 20



#endif //AIRRESPECK_STEP_COUNT_H
